use_frameworks!

target 'IJKMediaPlayer_Example' do
  pod 'IJKMediaPlayer', :path => '../'

  target 'IJKMediaPlayer_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
